name : Assignment 2
on:
  push:
    branches:
      - master

jobs:
  # -------------------------
  # Master job -> runs only on master branch
  # -------------------------
  master:
    name: Build and push (master)
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/heads/master')

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        
      - name: Build, tag and push image (master)
        uses: docker/build-push-action@v4
        with:
          context: ./Assignment-2/Backend/
          file: ./Assignment-2/Backend/Dockerfile.backend
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_REPO }}:dev-${{ github.run_number }}
 


